### ISSUE TITLE
Save

### ISSUE THREAD

**Issue by k1ycee** [hngi/deimos-solar-calculator-mobile-app#25]
So i found out that after the app is closed and opened again the app forgets all that the user had done, and that could really frustrate a user

**Comment by TobbyJay** [comment]
closed as in he added appliances but didn't calculate, and they decided to close the app and their progress did not save or......they are done  calculating and they close the app but the result/progress did not save, which? @k1ycee

**Comment by k1ycee** [comment]
I meant after calculating and leaving the result activity.

**Comment by TobbyJay** [comment]
yes , when a user closes the app, all information will be disposed off. no big deal there, it is a calculator remember?
