### ISSUE TITLE
App Design Issues

### ISSUE THREAD

**Issue by ngwutadesmond** [hngi/deimos-solar-calculator-mobile-app#8]
Hi everyone, so here's a little checklist of what out app needs and what is lacking:

- [x] Color is not consistent across the whole app's activities

- [x] Onboarding Screen is not following the simplest best practice

- [x] App need 3 colors max

- [x] We should agree on a design to avoid overdoing

Also somethings that needs quick fix are as follow:

- [x] SplashScreen takes longer than expected

- [x] Save the state if the user already seen onboarding screen it shouldn't come up again when they launch the app another time

**Comment by TobbyJay** [comment]
I can reduce the loading time of the splashscreen , the maximum loading time for a splashscreen is 3 seconds and i made it so, will look for a way to reduce the time asap, as for the colors, i am not really all that great with colors so maybe someone else can work on that, saving state( i can make it happen).

**Comment by ngwutadesmond** [comment]
Okay good, very good @TobbyJay

**Comment by chiboi-cesc** [comment]
great job @chydee and @TobbyJay

**Comment by Regulusbojah** [comment]
I guess the issue has been clarified. Most of us handling the designs ain't really designers.. we just picked from instinct.. all the same we are growing together ..Weldon bosses @chydee and @TobbyJay

**Comment by ngwutadesmond** [comment]
Has the on-boarding screen thing been fixex

**Comment by chiboi-cesc** [comment]
yes

**Comment by TobbyJay** [comment]
@chydee  everything has been fixed, all issues have been dealt with, thanks, kindly close.
